export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

import ClientProviders from './ClientProviders';
import ToastifyContainer from '@/components/ToastifyContainer';
import './globals.css';

export default function RootLayout({ children }) {
  return (
    <>
        <ClientProviders>{children}</ClientProviders>
        <ToastifyContainer />
    </>
  );
}
